/*
 * generated by Xtext 2.25.0
 */
package miniproject.dsl.markdown.web;

import com.google.inject.Guice;
import com.google.inject.Injector;
import miniproject.dsl.markdown.MarkdownDSLRuntimeModule;
import miniproject.dsl.markdown.MarkdownDSLStandaloneSetup;
import miniproject.dsl.markdown.ide.MarkdownDSLIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages in web applications.
 */
public class MarkdownDSLWebSetup extends MarkdownDSLStandaloneSetup {
	
	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new MarkdownDSLRuntimeModule(), new MarkdownDSLIdeModule(), new MarkdownDSLWebModule()));
	}
	
}
