/*
 * generated by Xtext 2.25.0
 */
package miniproject.dsl.markdown.web;


/**
 * Use this class to register additional components to be used within the web application.
 */
public class MarkdownDSLWebModule extends AbstractMarkdownDSLWebModule {
}
