/*
 * generated by Xtext 2.25.0
 */
package miniproject.dsl.markdown.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link MarkdownDSLWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractMarkdownDSLWebModule extends DefaultWebModule {

}
